language: node_js
dist: trusty
git:
  depth: 1
cache:
  edge: true
  directories:
    - node_modules
    - "$(npm root -g)"
    - "$(npm config get prefix)/bin"
branches:
  only:
    - master
    - stage
    - test
    - dev
env:
  global:
    - DEEP_NO_INTERACTION=1
    # CODECLIMATE_REPO_TOKEN=[secure]
    - secure: "N7qNjtPN73VyblSFVyAfPgsga5OWlnjK2plJsI8auiUZaXwxvbioQu/GaX/JgSqbRmG1oOkL8R/ciw2s8WAOHiUzFTx6udMLRWQdvW0JWvxq1UZVP4KO2GDuxSbMkRtukM0sSIDun7TKr91XDGdKjXrPiGbTmbYuYApuvtyu6XcTpw2rAjdnlLnmYsZtjb8QqhiFpFcRzvxmqBVimYxVHke/x1RVHdNtHkNzDIZ4qLXUcosPHhEFw19hegq2u8Pbaoa3RLz68QgA94Zjk5eawQV97Ah3TXYYTWspQcy5C4NYmKVpRMxhs0Vf5mwD58cVopf+M1aFdTOnK4WYwo1cSNv8N/4LqAwz9Xu5HyUuAr11Hucu6A3oiR8AIXvcHdULEPkDN6dbJzAouKd1upGpXQH4zdDei3z+WonGUyxrgKwx6T08Vm3knBVzPuvYEhE0XOomYOX7r6LEUf9QfXkyDXHh06PdlPVYFQS9NB2NBJWPvNIOs/rOV81u5BeAEUxpFxCzbORvHgxv++diPkboNWlXV1/dXdQR2bybPsgRD/DEav7OwjWcSuhm2lnpJpjORrTQSsi9TalJMKD4kMPoQ9kn3YgUm8xVbml2QcIJERNYg4GtQSzp5HkR8pISAVs+GXgP4qcc3NQAQ2UvON42m8bFaj4Jm/nRjWi6ibRgznA="
    # SNYK_API_TOKEN=[secure]
    - secure: "DoHoGKOcGJIZGGA256IF4xB6iDtVkPV8vPOMA7p9BckT67zuhCK584C0/UnJ6V09P81S2DA94pYYvkj6GWJs5nWVxPAvFRHe+oXbd0WN9WgSOB9ig1xd78Z5B1Wx4mdg9hcIdqWYu/ccT8VHl8odXOV2LW9VAWs0IMSEY6/ilWB3OGrUBXIIAOFIKrFz3ieU8lF2qeb0k9yl1u1BFwFVPLQOpceOOL6Sqqqw154qFnVF72y+Famu1ukBzElj13m2ie7oh0v2cFOm4aHEdBoxFYhcAEXJeYI1pv80PjnKHu7wzpavIJjQX+ikJDOVEaEkzkCaWkaHEs7g8j0Fy4fC6gL+MLS/J2QEH/Tlb64ocDI86Q+h/kbkXZMvY8B3XKSBP6kfXUFR3yN5VByukTmY7XOW1NH8HcOVMeY1wyEnztAbcmJPwZhvq6sEKhtE0H3lUiPv+8sDBuX1kdC9qPfLIAg3IoPefyopWLdX5EPNNK8eoyuEFUkEtMJVAuj5K6/7ao4e3Yw6BsQWzoT7Iu0+CJpoOqGIteDe1JeeNOpRtd6+laO6SMzEpYoq5LoGH+pR1W+2G24BhaFKp89TXxJ0wNrpkAk7lbwSow4U+nV+mRbq9tNGXQ9BzrxiYrlnMFHYotumD0HawRRxKvwi8LJqqu5liOmS3Cj0hNw1Vrkf24o="
    # AWS_DEFAULT_REGION=[secure]
    - secure: "Qv/N5UGQQNnS+7nBEMa1eIKN0pz6bsyjjH1eWi+QmXIB4OqF713WfgiNBlxz0ZiM2A69g91E5qsYLD7UQ5f5NWqJaWdHU67p0gTOXYr+Hz0GL1aYkKNWDR3x/1DO0P7nD0Pkz+Qsv3pOx7MP8cW8Yu7XLcj039FeuPDfmbKgxpAo5C+E9IutPEmH7CmUliezazQpS9Akzeua0DRMmS5CB0XWPwjUL30cK1VYQsaxCwfaJ1z9WXszMihGyEMHKuETnoUabrCimK1qKuzXaIm6YUExmReQBB1796RBl+jpVJJ23CB/o1DB1Z8WEyaALWgwNBA/bu5vr0GvGDe4cDB09iUjPV5dVXctWAzEF2Cvu3NrFMgpVsMP+bQIeYZp96fuLIN67wj5LQGo+dvqNqZMERP/si806kBoT0W0oZw3MfWtkQPDQkDe5b0rf8XuGdSGUwe+RXcKI4Dxj9Xd5cuk4PSol9HqnzCWUlHJTguBCEwArWp9wFu66yiSw7MdWuKRXo9qBMrZoNY9OuVJ1uwbFH/sdc14AwsHZo8UR0aSH5lQXirTI6+tlmqjkSEKy+iLEQollX71DuhLOM1m8PKjWEkQWn0Wi4CYvae0xk3VFwzhbQYuRj4d0MnNG9RMpcYdjLr/GryXYL5tJayH4B4CkyQhNQDgbYfmDUWMG1cEnKs="
    # AWS_ACCESS_KEY_ID=[secure]
    - secure: "pht93xCo49YSg/fkpKMw+i1ZPqbVPKezd8V/RC1qTi24bQ77C7iTKf/2LNI5D3q08l21QWmZNgoF7MDHYvtC5ntHnpnQlLdZZ38Rqcn/MRAf3efHoPQea8PbFjSGKAXm4JYaf0F5vCSLy0YSVKECvDAOYbVC7h6q7DI1A6Sc/+vqSzl0gXikHzr3vbp9aSEp+FfNE69+KmxFAZDM21bgdNn02E+hNR769VVNJs9ZCR6NU6Drk9yVs7uhlG3A0QqylrPu0efM+tqeRDNKS/5a5u5JNLxD0MLOIbLGJomlKxEwy1w/QBBXeWdN5gkLJsGGsYE2LkKoMBpouQIm7qwSQBxz8DaCtgjvHYTvOE33jsBmEVXhrRSIErBHUca8bllZAU3H+Odgf9AKDVsEcEZ4gGChN3yFafImzg+QbT7011AOMECBS8yaN6shOIyhMuuZfNFzR/wBzynjkLUhIqmOI2gpbVuCk9UKb3OAK9nFQbMCUpFrY8f8GWz46yYZUmRRPlzCMbvw+bP1gsPC+xYnyYixBsOJJg5rV6sLv5HkG/XIqub+jCSPb2QLJtmmjnsh9vvXL7OQOJz4iFPBQD9oRA1nmcHgxigBSDUz/YP1KgA+p83QLyRQVaTQ1J8T+fCdvJWkihGOipoWmke4OcfGNUwYQuAkhHB2jc8+c0K8hTY="
    # AWS_SECRET_ACCESS_KEY=[secure]
    - secure: "UnFFvC8b6MVxJNW/sKus38NuwCS30zcHcuOufrfHN9t4PaSJMjuue0ziu/K4J7yECJEnXLXA9T9Ms6bWoNtheM/zqtan9ofdICVB5Veg6BzYMLKdbwxrYn4sTvmBGYmhdcAjMHPyQ5zD06IuJRdrkEBUUevbN6Zt06oJ007uMa+UcUKKwANOxZTeKa+ArebkyVb/Epd2kO0gqGZfnxKgmHwmiaYnQsWYzv5PXqkmw3orwdzAY8a69iz7oewnXNdebq35lTXe8bGiTM20ORqsaR06pk5rfjy3PRg/EU/GfEgRCwnCjAsS3h3jZnMuBcKLLUpLSYDnP7LzzxehseY3Ws0sWQEE13sE3cSkiPQuraqWppVslbjbs2khTbgZTYQlkOa/Qh0BFOzX09+olpWJUCnyus6nQlDbHmWSRRpMSSUi+QweVpuJbVMbmRu9vFbagQAybLYJVrPtA6x4jER6nDD5GhxgTphW6GCvG96A9lV27U4zWgFm/HF+t1M/8erc3XZOTH+ZRZwLXNrNqthy+smPNGfQCJCGynUocHYa5eQ3gl6yhjG8NlUAohn3mM+QCzkQyOLdiZeeTlKsWHyQAypRFMrjX/WrT1qqiVbSj5Nt1OQVwerPGy/jxcdXoMHFRBCEByudZFy+aFykZqdncUP7J3wwEEMB85eGLtkQp8A="

stage: "Run Unit Tests :clipboard:"
node_js:
  - 6
  - 8
before_install:
  - bash bin/travis-init.sh
script:
  - recink run unit -c recink-codeclimate -c recink-snyk
