language: node_js
dist: trusty
git:
  depth: 1
cache:
  edge: true
  directories:
    - node_modules
    - "$(npm root -g)"
    - "$(npm config get prefix)/bin"
branches:
  only:
    - master
    - stage
    - test
    - dev
env:
  global:
    - DEEP_NO_INTERACTION=1
    # CODECLIMATE_REPO_TOKEN=[secure]
    - secure: "Qh9POfZ40nikOE4c+wlQWmJIcnuP9OR9zXpSOub28DcCnGmpEhn6sUCyXdaxaT/m+6rORSK9jnlVtAC1pSFQxD0MoZEM3+VVYT39/dj9YmCa9nxOIz2lMq94VqiOcQXCC6RT4zyE9I46RT4SZ/p2ZC95+Oip7RYjvrfMpdSgYm8FR3m70JeNiDtgTfFhxWZjxzUp6DanmnxZZzCOyWaKDdSyWBUEg0AEWfObCUezRCFCQXU1wratgQCgYWcFbTHYGuwIT51bxBGpW3q3l+IdFpg3/QDsugaYuW27pjEkVBhCcFpL2/QFtNxTxjjpfvZCF+WAfJS5SNIMjia5qXf9IkXHYyxrOnmTV9gv3hzh59eyOkolnMA4mKixl7YF5/hs24tmR5lQGLBD7xQ//3wVbIK2AD2c6C8fkVANLos7mWMtY011CR/O2o/RY9sMetr/osKgdAwkV5/Dolf3f8V2wvH1AHYbhA6Md8dtA2+8jY3HQ1TUtBVM5xWeu7PPyuHPoFKgU8UnHJmgxSYzofqTrWnR5YppFPKORVh6g69dUNRBZkt9m/9oYx6YJAR0c672TpPUikz28IFssDkzGImRcZsRf6gn4P1x5Rdtyy/H7xZfWbLloPXpgJ6LNzJYFhUrbrHqKL0M+ZbRCd4DIaT6hWap+C2/bJY+bbymNbQb+ts="
    # SNYK_API_TOKEN=[secure]
    - secure: "DoHoGKOcGJIZGGA256IF4xB6iDtVkPV8vPOMA7p9BckT67zuhCK584C0/UnJ6V09P81S2DA94pYYvkj6GWJs5nWVxPAvFRHe+oXbd0WN9WgSOB9ig1xd78Z5B1Wx4mdg9hcIdqWYu/ccT8VHl8odXOV2LW9VAWs0IMSEY6/ilWB3OGrUBXIIAOFIKrFz3ieU8lF2qeb0k9yl1u1BFwFVPLQOpceOOL6Sqqqw154qFnVF72y+Famu1ukBzElj13m2ie7oh0v2cFOm4aHEdBoxFYhcAEXJeYI1pv80PjnKHu7wzpavIJjQX+ikJDOVEaEkzkCaWkaHEs7g8j0Fy4fC6gL+MLS/J2QEH/Tlb64ocDI86Q+h/kbkXZMvY8B3XKSBP6kfXUFR3yN5VByukTmY7XOW1NH8HcOVMeY1wyEnztAbcmJPwZhvq6sEKhtE0H3lUiPv+8sDBuX1kdC9qPfLIAg3IoPefyopWLdX5EPNNK8eoyuEFUkEtMJVAuj5K6/7ao4e3Yw6BsQWzoT7Iu0+CJpoOqGIteDe1JeeNOpRtd6+laO6SMzEpYoq5LoGH+pR1W+2G24BhaFKp89TXxJ0wNrpkAk7lbwSow4U+nV+mRbq9tNGXQ9BzrxiYrlnMFHYotumD0HawRRxKvwi8LJqqu5liOmS3Cj0hNw1Vrkf24o="
    # AWS_DEFAULT_REGION=[secure]
    - secure: "Qv/N5UGQQNnS+7nBEMa1eIKN0pz6bsyjjH1eWi+QmXIB4OqF713WfgiNBlxz0ZiM2A69g91E5qsYLD7UQ5f5NWqJaWdHU67p0gTOXYr+Hz0GL1aYkKNWDR3x/1DO0P7nD0Pkz+Qsv3pOx7MP8cW8Yu7XLcj039FeuPDfmbKgxpAo5C+E9IutPEmH7CmUliezazQpS9Akzeua0DRMmS5CB0XWPwjUL30cK1VYQsaxCwfaJ1z9WXszMihGyEMHKuETnoUabrCimK1qKuzXaIm6YUExmReQBB1796RBl+jpVJJ23CB/o1DB1Z8WEyaALWgwNBA/bu5vr0GvGDe4cDB09iUjPV5dVXctWAzEF2Cvu3NrFMgpVsMP+bQIeYZp96fuLIN67wj5LQGo+dvqNqZMERP/si806kBoT0W0oZw3MfWtkQPDQkDe5b0rf8XuGdSGUwe+RXcKI4Dxj9Xd5cuk4PSol9HqnzCWUlHJTguBCEwArWp9wFu66yiSw7MdWuKRXo9qBMrZoNY9OuVJ1uwbFH/sdc14AwsHZo8UR0aSH5lQXirTI6+tlmqjkSEKy+iLEQollX71DuhLOM1m8PKjWEkQWn0Wi4CYvae0xk3VFwzhbQYuRj4d0MnNG9RMpcYdjLr/GryXYL5tJayH4B4CkyQhNQDgbYfmDUWMG1cEnKs="
    # AWS_ACCESS_KEY_ID=[secure]
    - secure: "d53To/VoZhENjCaCXe0hCo3SLl/lsN9JIEpwhat7vGjMRDFJZLKoZiIXCm0vzvXwwmiSWmihkzM9QAb5cIvM3P2Cmf1tYjZR3pc3um1ETQpGL4ImNwiS+gtxpu0K4JB0eSSw2CDapLhNQD1UEXxakOfiezrtWEfr2jqBM2XdQ2f+UhdpSp7GPDstMvq4fe6uFuL/47RdzSntoyyxfj5nuTE1nMuYLp9A7+8plh+tiwhVRFeE9ikIDX8yzNlGOLXUCRTmMlO80qT6tGPDdzEIAumv5eM6wdIhDrkzXaA6F75Y7yMeSJw+1vHES9R8LvHSqsft6MxeWOBHSFl4tiCVXHMofYQy3P1wSwE+ZCegZw1iT3igHeKCKNJZgnEiQXsRxL/P0AWmNMGun0rXbdWldW8XVyVzqi46plj4WNdVrHaWw44bN5fFX4+wKSE3IW10N55+P+lcNF8wus+jxjf5OKCItnP25+j6eZ0nPJ7ByKHWBYdpUyW7DmuNokXiIUukA5BUZ1yGywBAcxbXlpwkxbAFJsLsf+rdmPgsjDQyF7PYSqzxMYTtDc2ss7luc/ncznaeCpRZP3wC/4xkeOTnhW2r3ezE30qZLMYtx3ibHaP6wRyhFJy0e/YjW7+HD0XC2wPTpPIQqZqoy0UveevFKWBglCYL4oitED2QuxCYeK0="
    # AWS_SECRET_ACCESS_KEY=[secure]
    - secure: "RqL+GdaMIn0VklNvJCdRrTIscHPoPlNaKhfdv+tmfjKny1ylqmaC9btPMSKeJsbMhSd/MLIcMdmxwf+G7rETioqJXvI7HOsGkS2Bxkvxhk6KGux9198ShUqBXzkrt8HiDElDVPg5Y+E4SgitrRfB2lE2DZvYOZKqZQ2qODMdSstvFn0627Sto8AkXYDKhq4BL4mCPHY4xLeGPGmNmiBejfHMfXd38jk7uVu3egRCkiGO26lLkaCiNdqVA5iOS88sORK2ff3mcF8vvlpf087ZS85v0w5/zENX0hkH4Ho20CZjTG1DMmo3af0j5Pnxx7QQOCTurUhIFi65NLXh+FtFw8QFvX4ceRaPPCk1r6I+FPsFZo9EazCfcOnXeqmjRXOiTNbQJomHUPoIviAJ5tRqRi2HSZNH5PqGF2vfaoEHvoPbtnG+uY/+uBgg+UtkAUKR4c86gkrTYyhcYYfgbO3xo8J40nV6HYWfIlgf0xAI4U61EMnUxJpfBNwkHC2ZlTuIHXmaUDzvxbpdpWUx8+zuj9hc28wfvWc1PX8KdSQtdBpJwWj5ogD5li4+paMge38dHndNPqKD2goCQIcdgMkIvCTQvX/3oUOBkA2jqjpXgIU3Ul/ya+C3nUFqIRi9GouiU7I0vlq8bwvMweTrtGqArwMuU/iT9wf/361Bttt14FU="

stage: "Run Unit Tests :clipboard:"
node_js:
  - 6
  - 8
before_install:
  - bash bin/travis-init.sh
script:
  - recink run unit -c recink-codeclimate -c recink-snyk
