language: node_js
sudo: false
node_js:
- '0.12'
cache:
  directories:
  - $(npm root -g)
branches:
  only:
  - master
  - dev
  - stage
  - testing
env:
  global:
  #JSPM_GITHUB_AUTH_TOKEN=[secured]
  - secure: gsuvLVccy7ntUXaaUEydprckao0ADGjZPpj/L1lyj0LUXDM6bV8y8OFCaz44dy9ITSB/lk6g7JwxON6UoS/c84Uja2M3Rv02IcZv+3iz1l+he38B3Qph/0XLVySPYARRd4Md7yoqNFH0j88ScCZmpySoMFoHivq4Cc4KuuuN4DunxBtWdue3J7wOe6odPuj6QPNkzBNfCEjG+gtC9t/qWHTChNdA/fGEkr+4dqeiQDqfkmRYpoeC3S4GT8zlx0lJ9NfJKPjxw/ubUnGo+RxD/hXNQCBNnvkO5WaGYVH7fDOTuFKTDpa9+8G6JUbkN1iYbLn14PZbAMePlUOLvGFw37dISfcF7JGg+Kqdz5XKPEcQrlgABAJO/0/FeGBR/JKQxOPF8YhYxVgcC6e7snuVexkyiOY4sJTZL/zYoaXiUXLdShWQeiq5ABtZOYtXkI7IlIBjGmXm/jiYqBnaujeJqMihyOaRl6B9O4p1rPMGKzYi2/6gce0A+Hez9PnipCwCa1wU8Bcn4lJwFLP0aFoLyKCL4oSTMKs6DuHeC/IlWB6tN3FYWBzcHRMZnNrY0CoYABVbKU/teNEdzqtxoIjZhqE0EmTC9w+hYgkhG/JU+eZVPdIdDXuDzMO+A+cfgD94Ae//jL8SXOkCjF3DISgJzewIscAKdvQuZgJztQqw8Tc=
  #COVERALLS_SERVICE_NAME=[secured]
  - secure: D8C4oPSeE+s2hWzu0qE92FKH5dBdvCQ/wfb/W6YiLzhct0ymhnx2TXnTMelsCsGXHJSfZvT22I2BdxKJh3H+QvWkQilqSxCLigoGJzziLy1+d4neZbs2iSPv3wLC22e6aW5dKiSjkLtHcOLwppaY6di3lD4iYtmZcLzhKDQ8lw3UhrPCe4Sos9m16FlNgEcvJKuqYSOA9Q33hynnibc+cqOlns/9YHkOiZ4af/j8J74thM9jqck7Hst5E/DLDQAXk1Hi6Vi8Ua/BifaxtMeNnqXk9mfXUQIe5GnTNbQ8r5jDn/8OyxQuwd4QUVK2dQoLQjmBRI0JKy6Ojx7os7lCUAAIKA1NL4vXI0LfSQtUGI36V7z9w8kK9SsMzCe/Qc5sSEWkoqS4zkxV8bjn9O24rgO+daRj1/TxVitsF8GVHERyRYuG+oJoviNEDGHFnZ1NFUanDFjObbNazNDh/IlLqUpjA5VB+9msre4VXtekmYS7taontID0G/Nyh6d8UdIx1VVPoHw2lyP82xT/ZPNIUMhPywtTAe2nGYykXYNbusxYyLucNLB56KKofmm6hgZD/pxrge4XS8f8lHd06xKefYpGOedh3QVcjU8ziuQ9JwcYPoFTghvt7kLJiR4Ogfk5p6PlNoJkK7I78kepjErx9WolhC1hhjYv2JkSvTARuyw=
  #COVERALLS_REPO_TOKEN=[secured]
  - secure: MYn+dG0RMd9ZQsWguwI4ujkfTZlTM+uQNkXhFqmfHlPM5npUm7nps7OxigmOKZAkUw9D3Kfq4S1YcVVKOnpUk3zWFOFnYp87Kwn2K4l0tK+TwzQNy0i5NJu1iLfNEg++to1k114irsbWjsA849XCiI+W5q7f6W4LgSt/PhO1WeqpVefykrnldTG/9fhCk8s11zU/sb6jbCMn2wX1DFmsf+ihtsExKRPt/xImS7bcTrmPy86/h4WYLr9MBP4MERH4A7IZuL6VFQRAcIpy9Fn7PxDzoyY42vZGZufaKckCkwnKxtpkBsmvDR5tRYPGPxIJR5zvsj1B/iY8GaCI+K1HV+ahI7xFF57v1TI43EdS6tvJFosAsSnCz7OvjbvAxIrueO8LHFU7HXCC93TqJwIByWOXzSL9XJ0NtuniAT5qMXAVCfVGRKNYa1DbrNJxG09d0Bnd8VrwReIm+gcTMv86ErtMZ6TaCo66WCRZqqeVEew0e7VWRGWdwDFkWBtIPvx612ZyD4fIHUI4df7qp96CzzUdzub0ZPComw68MKOi9aVMbw2rdxxc/w3SLRvsjsM74mZ7ZBzuZAJ5erFH1ic5FoaGXu5/jG6wJSveZ5CIC8ieINrKbVLJQUvzOZjE049QymzrNHWJoGhpR1HOV4D2d5FRY3m5qpKLrVcEG7FmNA0=
  #CODACY_PROJECT_TOKEN=[secured]
  - secure: i6DYnNlhKrlxs4OIqn8IN3HRXPv2zy5xPeB8QNJ0Oo1OShBzf3+WrbukG/7fykHtYzBBFMg/COBOWtP/r11XY96DOhOl/zq+LR+puPC+Pj+frCJuvCzfWGmgoUYgajM+JYgPn75YdRM9ge0xB9olSBYmQxPVCZ2NYKAizmOTnsIIvL5sIvo9us8wwIeNhJdFDzWnNeKDLTqfwMqo7gX9hSE7w50ZLX2KOa+ze8kcA/ouFj/VQE3icSc6jAjQmkSx1yuFGAaUmMCxAZX9MECFGt6geCtL5wM601moOIuEhq5giYJUHZI0CIKeo4aGX/PX41nfocmbT51NIO/Hgy4uPKBBbjiBkymtbC/+803dEktUqxwJvTLERIBUjo/Gz86BFExehdTLpMMz3P9MOvDe6L8Xn5zHLwoblAjcFlcXOrFgRLk68hRtJQ3ycUdRpROHLLF9cWSY0wKKzCgVudazgbRc4IO/+1TPG1wYB2/Fw3999Xb9KcyHsCMmc8uGR24SuCvQfy3SgKYbJwOJGd3WSfQkJliZaWsEqH8/pcSxlBhEdqDYrN87cCHAp6XcpC/GQWiLRS9TMlBdf2m/YJJUcSxcs6DzFky581CjFKFQsoc4TR5kzp0CKyzEOeR88WW8A6/rtC6iGZnqoEdBpNYVa1B4Wdu4MNGTFdoNraJjYlo=
before_install:
- npm install -g jspm
- jspm config registries.github.auth $JSPM_GITHUB_AUTH_TOKEN
- npm install -g babel
- npm install -g browserify
- npm install -g mocha
- npm install -g mocha-babel
- npm install -g istanbul
- npm install -g coveralls
- npm install -g isparta
- npm install -g codacy-coverage
- npm install -g istanbul-combine
- npm install -g jasmine-core
- cp test/package.json .
after_success:
- npm run coverage
