language: node_js
sudo: false
node_js:
- '0.12.4'
cache:
  directories:
  - $(npm root -g)
branches:
  only:
  - master
  - dev
  - stage
  - testing
  - unit-testing
env:
  global:
  #JSPM_GITHUB_AUTH_TOKEN=[secured]
  - secure: i6CA8L19Qb2UPbKb1eshPJ/pGgswKAehXCPFiJDknkGiSP+TO+e6nutA69UIkFTLQ9iulNVNcWw/uIUO0r2XRhkOoq9CnST/Fu/Te4fb4E9Is+0Lm/F/72HWJ91wm/1gZm/2pK4bMTkpLtG+pb0lu8B2H5tER5RiUBB/8Q8i+6tMFucqMwZ3Qb8VPJZgRK0gjo15Zm5oVIHDJ2XIvW+rfuoPXW0zoIECIhghbsbXfvsFuKIIHUn083oT7zuyuszYqNq8Y7Kf2NyvGA2oconNBWzTbf6/lQG0QnVmZAUqB/owbs9iUgb1moIuX3+ONKVzyijaOQCuqwqFHgB2gu2xcZ23qA5eMN8Db+6GZMT9vUIxeR/gfWUuUS5rqsKpaN6XNq/eo1Pw7ZCgKPCGEcnwyfTuoPFCxxk3eV1FjEuLqweGiD08yrVyaX+9DuLr4mCB8YwcPAzM4hBD+B0y/svqnHXqh40Ghwg+6pfWa0M5ZbXtKZKqfhExauWpKfCLsEuO60PS6S4S/fhxGC0MV/XBHZiwpUJ7tbYbjowvdJsuQArvr2Sq3hFbU1FZcylczbdDyAJTQtuz2RLdZ95P98FiP7H7y+SXpfhiJMUN/Z0FruCMQMOD9pXGp1R531WY2yAfvlrySfD1oH3leaEk0YzfnBBAXRe2ROKh4s1UI37UIx4=
  #CODACY_PROJECT_TOKEN=[secured]
  - secure: i6DYnNlhKrlxs4OIqn8IN3HRXPv2zy5xPeB8QNJ0Oo1OShBzf3+WrbukG/7fykHtYzBBFMg/COBOWtP/r11XY96DOhOl/zq+LR+puPC+Pj+frCJuvCzfWGmgoUYgajM+JYgPn75YdRM9ge0xB9olSBYmQxPVCZ2NYKAizmOTnsIIvL5sIvo9us8wwIeNhJdFDzWnNeKDLTqfwMqo7gX9hSE7w50ZLX2KOa+ze8kcA/ouFj/VQE3icSc6jAjQmkSx1yuFGAaUmMCxAZX9MECFGt6geCtL5wM601moOIuEhq5giYJUHZI0CIKeo4aGX/PX41nfocmbT51NIO/Hgy4uPKBBbjiBkymtbC/+803dEktUqxwJvTLERIBUjo/Gz86BFExehdTLpMMz3P9MOvDe6L8Xn5zHLwoblAjcFlcXOrFgRLk68hRtJQ3ycUdRpROHLLF9cWSY0wKKzCgVudazgbRc4IO/+1TPG1wYB2/Fw3999Xb9KcyHsCMmc8uGR24SuCvQfy3SgKYbJwOJGd3WSfQkJliZaWsEqH8/pcSxlBhEdqDYrN87cCHAp6XcpC/GQWiLRS9TMlBdf2m/YJJUcSxcs6DzFky581CjFKFQsoc4TR5kzp0CKyzEOeR88WW8A6/rtC6iGZnqoEdBpNYVa1B4Wdu4MNGTFdoNraJjYlo=
before_install:
  - npm install -g jspm
  - jspm config registries.github.auth $JSPM_GITHUB_AUTH_TOKEN
  - npm install -g babel
  - npm install -g browserify
  - npm install -g jscs
  - npm install -g mocha
  - npm install -g mocha-babel
  - npm install -g codacy-coverage
  - npm install -g istanbul
  - npm install -g istanbul-combine
  - npm install -g jasmine-core
  - npm install -g karma
  - npm install -g karma-coverage
  - npm install -g karma-chrome-launcher
  - npm install -g karma-jspm
  - npm install -g karma-ng-html2js-preprocessor
  - npm install -g karma-phantomjs-launcher
  - npm install -g karma-traceur-preprocessor
  - npm install -g karma-verbose-reporter
  - npm install -g phantomjs
  - npm install --save-dev karma-coverage
  - npm install --save-dev karma-babel-preprocessor
  - npm install --save-dev karma-jasmine
  - npm install --save-dev douglasduteil/karma-coverage#next
  - npm install --save-dev isparta
  - cp test/package.json .
after_success:
  - npm run coverage
