language: node_js
sudo: false
node_js:
  - 0.12
cache:
  directories:
    - $(npm root -g)
branches:
  only:
    - master
    - dev
    - stage
    - testing
env:
  global:
    #JSPM_GITHUB_AUTH_TOKEN=[secured]
    - secure: MEwysS3HqSUfT/7AnpgqYpZXyFkXQSQDH0YsoA0lUO+tJyIHLrEuJuEIHEazKvD7VYbQNBYjJYf92uTxh1egakH60eC/QyrluFSqu5KFtpx/lnyfMNkl7feld+jQxO7kXKGxhjaqxmhn2Gp/42tV+FUFb7dU3kZgh0R6vCluado9Vm1tWwVjRUYVEzp2avRwolBsn5xqLVVvMakulEOKT4py5/Pmnm9iZEGWBw+0dIxdtWTQDGDCHshcdTP7QxcWWUe7B9P979M24ePSmmQC9jFLAQo7JCvj6fJW+gNK590XmJZKNmtpdG+Jo8rjhRjbUaeUzaZsw15aJoFuUsrfdxuNKtAYDZ92q2390FAF0czYBIBRwsiLcIS6P3Lsf5Tbq0WTLrEU7cTKwAmB3jEiNXPY+3OkkqT5kGmwKzEp0LgR7d/Ht/iecXSfzrP5Am4XYtOUPsRn9kig0t4Zb6iHyrAc+Zvnb3FzLMSSllayTAcXF9wHvqSeSdJ3qN2vUMEXN5KNWIkcGMiqQD6g0Jcgdl0MHOBSrgjzJQKJpLYVObP/tlsDaxUyIHgqjEQtXSnRIW4cNoOwgk9ltpzWBtT0z+DW6A/tDNcc2y7ejX7bjHSXxxWAk/jNjCAaYPINiWu+HL6UoPjnwiy7NOlJRMXoS7zR0Gmqr0cfKl1+VVIPP90=
    #CODACY_PROJECT_TOKEN=[secured]
    - secure: i6DYnNlhKrlxs4OIqn8IN3HRXPv2zy5xPeB8QNJ0Oo1OShBzf3+WrbukG/7fykHtYzBBFMg/COBOWtP/r11XY96DOhOl/zq+LR+puPC+Pj+frCJuvCzfWGmgoUYgajM+JYgPn75YdRM9ge0xB9olSBYmQxPVCZ2NYKAizmOTnsIIvL5sIvo9us8wwIeNhJdFDzWnNeKDLTqfwMqo7gX9hSE7w50ZLX2KOa+ze8kcA/ouFj/VQE3icSc6jAjQmkSx1yuFGAaUmMCxAZX9MECFGt6geCtL5wM601moOIuEhq5giYJUHZI0CIKeo4aGX/PX41nfocmbT51NIO/Hgy4uPKBBbjiBkymtbC/+803dEktUqxwJvTLERIBUjo/Gz86BFExehdTLpMMz3P9MOvDe6L8Xn5zHLwoblAjcFlcXOrFgRLk68hRtJQ3ycUdRpROHLLF9cWSY0wKKzCgVudazgbRc4IO/+1TPG1wYB2/Fw3999Xb9KcyHsCMmc8uGR24SuCvQfy3SgKYbJwOJGd3WSfQkJliZaWsEqH8/pcSxlBhEdqDYrN87cCHAp6XcpC/GQWiLRS9TMlBdf2m/YJJUcSxcs6DzFky581CjFKFQsoc4TR5kzp0CKyzEOeR88WW8A6/rtC6iGZnqoEdBpNYVa1B4Wdu4MNGTFdoNraJjYlo=
before_install:
  - npm install -g jspm
  - jspm config registries.github.auth $JSPM_GITHUB_AUTH_TOKEN
  - npm install -g babel@5.8.19
  - npm install -g browserify@11.2.0
  - npm install -g jscs@2.1.1
  - npm install -g mocha@2.3.3
  - npm install -g mocha-babel@3.0.0
  - npm install -g codacy-coverage@1.1.3
  - npm install -g chai@3.3.0
  - npm install -g jasmine-core@2.3.4
  - npm install -g istanbul@0.3.21
  - npm install -g istanbul-combine@0.3.0
  - npm install -g phantomjs@1.9.18
  - npm install -g karma@0.13.11
  - npm install -g karma-jspm@2.0.1
  - npm install -g karma-jasmine@0.3.6
  - npm install -g karma-babel-preprocessor@5.2.2
  - npm install -g karma-coverage@douglasduteil/karma-coverage#next
  - npm install -g karma-verbose-reporter@0.0.3
  - npm install -g karma-phantomjs-launcher@0.2.1
  - npm install -g karma-ng-html2js-preprocessor@0.2.0
  - cp test/package.json .
after_success:
  - npm run coverage
